### ISSUE TITLE
Adblockers are going to block the script to load library from cdn

### ISSUE THREAD

**Issue by andirsun** [mixpanel/flask-tracking-proxy#3]
https://github.com/mixpanel/flask-tracking-proxy/blob/1d153d6ee0213c6e75de0f039f370a93a7cd9c46/example.html#L21C2-L21C2

The url ```cdn.mxpnl.com``` is going to be blocked by adblockers so this strategy is not going to work at all.

**Comment by ak--47** [comment]
@andirsun see: https://github.com/mixpanel/tracking-proxy/issues/13#issuecomment-1719661660

tldr;

add
```javascript
const MIXPANEL_CUSTOM_LIB_URL = "https://<YOUR_PROXY_DOMAIN>/lib.min.js";
```

_before_ the snippet and everything will work!

**Comment by andirsun** [comment]
Fixed on https://github.com/mixpanel/tracking-proxy/issues/13#issuecomment-1719661660
